# Generated by Django 5.2.14 on 2026-05-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_orders", models.IntegerField(default=0)),
                ("completed_orders", models.IntegerField(default=0)),
                ("cancelled_orders", models.IntegerField(default=0)),
                ("pending_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_items_sold", models.IntegerField(default=0)),
                ("unique_customers", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد المعالجة"),
                            ("PROCESSING", "جاري المعالجة"),
                            ("COMPLETED", "مكتمل"),
                            ("FAILED", "فشل"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("chunks_processed", models.IntegerField(default=0)),
                ("batch_size", models.IntegerField(default=100)),
                ("processing_time_seconds", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تقرير المبيعات اليومي",
                "verbose_name_plural": "تقارير المبيعات اليومية",
                "ordering": ["-date"],
            },
        ),
    ]
