# Generated by Django 5.2.13 on 2026-06-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailysalesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedLockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('lock_id', models.CharField(max_length=36)),
                ('acquired_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Distributed Lock',
                'verbose_name_plural': 'Distributed Locks',
                'db_table': 'distributed_locks',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
