# Generated by Django 5.2.13 on 2026-06-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_distributedlockmodel_product_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistributedLockModel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
    ]
