# Generated by Django 5.2.13 on 2026-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_distributedlockmodel_remove_product_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
